# "make" to run the game
# "make clean" to clean all .class files

prog: my.class 
	appletviewer BirdGamePackage.html

my.class: BirdGamePackage
	javac ./BirdGamePackage/*.java

make clean:
	rm ./BirdGamePackage/*.class