# make to compile Bird Sim
# make run to run Bird Sim
# make clean to clean all .class file

my.class: Animation ELements MainFrame
	javac Animation/*.java ELements/*.java MainFrame/*.java

run:  
	java -jar ClickMe.jar

make clean:
	rm Animation/*.class ELements/*.class MainFrame/*.class